services:

  nginx:
    volumes:
      - static_volume:/var/www/html/staticfiles/

  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    restart: unless-stopped
    volumes:
      - minio_data1:/data1
      - minio_data2:/data2
      # - minio_data3:/data3
      # - minio_data4:/data4
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # MINIO_BROWSER_REDIRECT_URL: http://${QFIELDCLOUD_HOST}:${MINIO_BROWSER_PORT}
      MINIO_BROWSER: ${MINIO_BROWSER}
    # command: server /data{1...4} --console-address :9001
    command: server /data{1...2}
    healthcheck:
        test: ["CMD", "mc", "alias", "set", "minio", "http://localhost:9000", "$MINIO_ROOT_USER", "$MINIO_ROOT_PASSWORD"]
        interval: 60s
        timeout: 20s
        retries: 5
    ports:
      # - 172.17.0.1:9001:9001
      - 172.17.0.1:9000:9000

  createbuckets:
    build:
      context: ./docker-createbuckets
    depends_on:
      minio:
        condition: service_healthy
    environment:
      STORAGES: ${STORAGES}

volumes:
  minio_data1:
  minio_data2:
  # minio_data3:
  # minio_data4:
